### ISSUE TITLE
perf: improve the API response time

### ISSUE THREAD

**Issue by cre8ivejp** [bucketeer-io/javascript-client-sdk#87]
## Summary

We are improving the evaluation process on the server to evaluate only the flags that have been changed.
This will improve the load on the server and the response time since it will only return the flags that have been changed.

Currently, when a flag changes on the server, it evaluates all flags again and sends the latest evaluations to the client SDK.
The SDK checks the response and does nothing if the response is empty. Otherwise, it deletes all the data in the local storage and saves the latest evaluations.

### When the SDK is initialized

1- Change the `featureTag` setting to be optional in the `BKTConfig`
2- Save the `featureTag` in the `localStorage` if it is configured in the `BKTConfig`
3- Clear the `userEvaluationsID` in the `localStorage` if the `featureTag` changes

### When sending requests

The following new fields will be added to `get_evaluations` request.

- **evaluatedAt**: the last time the user was evaluated. The server will return in the get_evaluations response (`UserEvaluations.CreatedAt`), and it must be saved in the client
- **userAttributesUpdated**: when the user attributes change via the `customAttributes` interface, the userAttributesUpdated field must be set to true in the next request

### When getting the response (Update conditions)

The server will return the new following fields in the response.

- **forceUpdate**: a boolean that tells the SDK to delete all the current data and save the latest evaluations from the response
- **archivedFeatureIds**: a list of feature flag ids that were archived on the admin console. All those feature flags must be deleted from the local storage.

#### forceUpdate is True

1- Delete all the evaluations from local storage, and save the latest evaluations from the response into the local storage
2- Save the `UserEvaluations.CreatedAt` in the response as `evaluatedAt` in the `localStorage`

#### forceUpdate is false

1- Check the evaluation list  in the response and **upsert** them in the `localStorage` if the list is not empty
2- Check the `archivedFeatureIds` list and delete them from the `localStorage` if is not empty
3- Save the `UserEvaluations.CreatedAt` in the response as `evaluatedAt` in the `localStorage`

**Comment by yshrsmz** [comment]
@cre8ivejp Can we make a `/get_evaluations` request if `featureTag` is not set?

**Comment by cre8ivejp** [comment]
@yshrsmz 

> Can we make a /get_evaluations request if the featureTag is not set?

Yes. It will evaluate and return all the feature flags (android, js, ios, go-server, etc) in the environment. But I just found that when the `featureTag` is empty and the `evaluatedAt` is zero, it validates the `featureTag`, causing an error. I'll fix this today.

> In the first request to the /get_evaluations, what should we send as a evaluatedAt?

We should send it as zero. We will need to send it as an object. Same for `userAttributesUpdated`.
I'll let you know the object type as soon as we fix the server. 

E.g.
https://github.com/ca-dp/bucketeer-node-server-sdk/pull/15/files#diff-213cc68bda5e3015ffa9ff47d8a5fd517340cdafd6bcf3f4ab23bac6d011b7c6L128-L131

> Regarding userAttributesUpdated, what should we send as a first call upon app launch?

You can send it as false.

> user attributes can be different from the last request, but we have no idea about it.

If the request has the `userAttributesUpdated` set to true, and during the request, the app updates it again, we should also send it as true in the next request. But this could be complicated to do.

Perhaps, to keep it simple, if we change the implementation to request the evaluations at the time the `userAttributesUpdated` changes, it would be easier instead of waiting for the next poll interval.

Please let me know what you think.

**Comment by yshrsmz** [comment]
Thanks, that solved my concerns for now.

I'm thinking about changing the SDK's API a bit.

```ts
const user = defineBKTUser({...})

// remove featureTag from BKTConfig
const config = defineBKTConfig({...})

// pass FeatureTag as a separate argument.
// I'm planning to add overloads if possible.
initializeBKTClient(user, config, featureTag, timeout)
initializeBKTClient(user, config, timeout)
initializeBKTClient(user, config)

const client = getBKTClient()!

// get current FeatureTag
const current = client.currentFeatureTag()

// update FeatureTag
client.updateFeatureTag('newFeatureTag')
```

- BKTConfig is currently holding immutable values.
- FeatureTag becomes optional and now mutable; it's kind of strange that BKTConfig holds a mutable value.

What do you think about this?

**Comment by yshrsmz** [comment]
@cre8ivejp 

Thanks, that solved my concerns for now.

I'm thinking about changing the SDK's API a bit.

```ts
const user = defineBKTUser({...})

// remove featureTag from BKTConfig
const config = defineBKTConfig({...})

// pass FeatureTag as a separate argument.
// I'm planning to add overloads if possible.
initializeBKTClient(user, config, featureTag, timeout)
initializeBKTClient(user, config, timeout)
initializeBKTClient(user, config)

const client = getBKTClient()!

// get current FeatureTag
const current = client.currentFeatureTag()

// update FeatureTag
client.updateFeatureTag('newFeatureTag')
```

- BKTConfig is currently holding immutable values.
- FeatureTag becomes optional and now mutable; it's kind of strange that BKTConfig holds a mutable value.

What do you think about this?

**Comment by cre8ivejp** [comment]
@yshrsmz

I agree.
As long we don't introduce breaking changes in the SDKs (Android, iOS, JS), sounds good to me.

**Comment by yshrsmz** [comment]
@cre8ivejp 
No, it's a breaking change, as `defineBKTConfig` no longer accepts `featureTag` parameter.

**Comment by cre8ivejp** [comment]
@yshrsmz 
I see.
How about keeping the BKTConfig as it is, and when the developer wants to change the feature tag, he initializes the SDK again?
Like when we want to change the end user id. Usually, the user won't change the tag after initializing the SDK.

**Comment by yshrsmz** [comment]
@cre8ivejp Sounds good to me.

If we basically want developers to set `featureTag`, keeping `featureTag` required makes it less miss-usable 👍
